# Car Image Editor Configuration

# Model settings
models:
  use_sam: false  # Enable for better segmentation
  use_ai_background: false  # Enable for AI-generated backgrounds

# Processing settings
processing:
  alpha_matting: true
  shadow_generation: true
  auto_white_balance: true

# Enhancement settings
enhancement:
  sharpen_amount: 1.2
  contrast_boost: 1.2
  brightness_adjust: 1.1
  color_saturation: 1.1

# Logo settings
logo:
  font_size: 40
  font_color: [255, 255, 255]
  shadow_offset: 2
  shadow_color: [0, 0, 0, 128]

# Output settings
output:
  quality: 95
  format: "JPEG"

# Beautify settings
beautify:
  enable: true
  effects:
    glossy_paint: true
    stain_removal: true
    soft_reflections: true
  model:
    controlnet: true
    stable_diffusion: true
    lora_trained_on_cars: true
  output_quality: "professional"
  
# AI Beautifier advanced settings
ai_beautifier:
  default_enhancement_level: "medium"  # light, medium, strong
  default_style: "glossy"  # glossy, matte, metallic, luxury
  inference_steps: 25
  guidance_scale: 7.5
  controlnet_conditioning_scale: 0.8
  memory_optimization: true
  fallback_to_traditional: true
  styles:
    glossy:
      description: "Mirror-like reflections, wet look"
      enhancement_factor: 1.2
    matte:
      description: "Smooth elegant finish"
      enhancement_factor: 0.9
    metallic:
      description: "Pearl finish with sparkle"
      enhancement_factor: 1.1
    luxury:
      description: "Premium showroom quality"
      enhancement_factor: 1.3
